//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountableForm_Inventory
    {
        public int AFORID { get; set; }
        public int AccountFormID { get; set; }
        public int StubNo { get; set; }
        public int Quantity { get; set; }
        public int StartingOR { get; set; }
        public int EndingOR { get; set; }
        public System.DateTime Date { get; set; }
        public bool isIssued { get; set; }
    
        public virtual AccountableFormTable AccountableFormTable { get; set; }
    }
}
