//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundType_FundType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FundType_FundType()
        {
            this.FundType_FundTypeTable = new HashSet<FundType_FundTypeTable>();
        }
    
        public int FundTypeID { get; set; }
        public string FundTypeTitle { get; set; }
        public Nullable<int> FundID { get; set; }
    
        public virtual FundType_FundName FundType_FundName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundType_FundTypeTable> FundType_FundTypeTable { get; set; }
    }
}
