//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundType_FundTypeTable
    {
        public int ListFundTypeID { get; set; }
        public int FundID { get; set; }
        public int FundTypeID { get; set; }
        public string FundParticulars { get; set; }
    
        public virtual FundType_FundType FundType_FundType { get; set; }
    }
}
