//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRA_Table
    {
        public int IRAID { get; set; }
        public decimal IRAPercentageShare { get; set; }
        public int IRAPercent { get; set; }
        public decimal IRABase { get; set; }
    }
}
