//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoAccClassTable
    {
        public int MemoAccClassID { get; set; }
        public int RevisionYear { get; set; }
        public int AccountCodeID { get; set; }
    
        public virtual MemoAccClass_AccountCode MemoAccClass_AccountCode { get; set; }
    }
}
