//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFund
    {
        public int SubFundID { get; set; }
        public Nullable<int> FundID { get; set; }
        public string SubFundName { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
