//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSector
    {
        public int SubSectorID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string SubSectorName { get; set; }
        public string SubSectorCode { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
